name: Build

on:
  push:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build success"
